#ifndef LT_SCREEN_KEYS_H
#define LT_SCREEN_KEYS_H

#define LTSCREEN_KEY_ENTER              0x0001U
#define LTSCREEN_KEY_VERSION_UPDATE     0x0003U
#define LTSCREEN_KEY_USER_STATUS        0x0004U
#define LTSCREEN_KEY_OPEN_DEVICE        0x0005U
#define LTSCREEN_KEY_START_CALIBRATION  0x0006U
#define LTSCREEN_KEY_START_TRAINING     0x0007U
#define LTSCREEN_KEY_UPDATE_START       0x0021U
#define LTSCREEN_KEY_BACK               0x0022U
#define LTSCREEN_KEY_WIFI_CHANGE        0x0023U
#define LTSCREEN_KEY_INNER_START_TRAIN  0x0042U

#endif /* LT_SCREEN_KEYS_H */
