#ifndef __UART7_ROLE_H
#define __UART7_ROLE_H

#define UART7_ROLE_DEBUG  0U
#define UART7_ROLE_SCREEN 1U

#define SCREEN_TEST_MODE_HEALTH_MONITOR   0U
#define SCREEN_TEST_MODE_COMPONENT_PROBE  1U

#define SCREEN_ISOLATION_TEST_OFF 0U
#define SCREEN_ISOLATION_TEST_ON  1U

#define UART7_SCREEN_RAW_PROBE_OFF 0U
#define UART7_SCREEN_RAW_PROBE_ON  1U

//注意这个串口7针对的是网络调试和屏幕驱动的角色选择，不能随意更改，否则会导致串口7的功能异常。
//串口打印往串口2
#ifndef APP_UART7_ROLE
#define APP_UART7_ROLE UART7_ROLE_SCREEN
//#define APP_UART7_ROLE UART7_ROLE_DEBUG
#endif

#ifndef APP_SCREEN_TEST_MODE
#define APP_SCREEN_TEST_MODE SCREEN_TEST_MODE_HEALTH_MONITOR
#endif

#ifndef APP_SCREEN_ISOLATION_TEST
#define APP_SCREEN_ISOLATION_TEST SCREEN_ISOLATION_TEST_OFF
#endif

#ifndef APP_UART7_SCREEN_RAW_PROBE
#define APP_UART7_SCREEN_RAW_PROBE UART7_SCREEN_RAW_PROBE_ON
#endif

#if ((APP_UART7_ROLE != UART7_ROLE_DEBUG) && (APP_UART7_ROLE != UART7_ROLE_SCREEN))
#error "APP_UART7_ROLE must be UART7_ROLE_DEBUG or UART7_ROLE_SCREEN"
#endif

#if ((APP_SCREEN_TEST_MODE != SCREEN_TEST_MODE_HEALTH_MONITOR) && \
     (APP_SCREEN_TEST_MODE != SCREEN_TEST_MODE_COMPONENT_PROBE))
#error "APP_SCREEN_TEST_MODE must be SCREEN_TEST_MODE_HEALTH_MONITOR or SCREEN_TEST_MODE_COMPONENT_PROBE"
#endif

#if ((APP_SCREEN_ISOLATION_TEST != SCREEN_ISOLATION_TEST_OFF) && \
     (APP_SCREEN_ISOLATION_TEST != SCREEN_ISOLATION_TEST_ON))
#error "APP_SCREEN_ISOLATION_TEST must be SCREEN_ISOLATION_TEST_OFF or SCREEN_ISOLATION_TEST_ON"
#endif

#if ((APP_UART7_SCREEN_RAW_PROBE != UART7_SCREEN_RAW_PROBE_OFF) && \
     (APP_UART7_SCREEN_RAW_PROBE != UART7_SCREEN_RAW_PROBE_ON))
#error "APP_UART7_SCREEN_RAW_PROBE must be UART7_SCREEN_RAW_PROBE_OFF or UART7_SCREEN_RAW_PROBE_ON"
#endif

#define APP_UART7_IS_DEBUG  (APP_UART7_ROLE == UART7_ROLE_DEBUG)
#define APP_UART7_IS_SCREEN (APP_UART7_ROLE == UART7_ROLE_SCREEN)
#define APP_SCREEN_IS_HEALTH_MONITOR  (APP_SCREEN_TEST_MODE == SCREEN_TEST_MODE_HEALTH_MONITOR)
#define APP_SCREEN_IS_COMPONENT_PROBE (APP_SCREEN_TEST_MODE == SCREEN_TEST_MODE_COMPONENT_PROBE)
#define APP_SCREEN_ISOLATION_ENABLED  (APP_SCREEN_ISOLATION_TEST == SCREEN_ISOLATION_TEST_ON)
#define APP_UART7_SCREEN_RAW_PROBE_ENABLED (APP_UART7_SCREEN_RAW_PROBE == UART7_SCREEN_RAW_PROBE_ON)

#endif /* __UART7_ROLE_H */
